### ISSUE TITLE
Bad manifest for sys-kernel/ck-sources

### ISSUE THREAD

**Issue by invakid404** [Pross/pross-overlay#1]
Manifest for sys-kernel/ck-sources must be regenerated, as it contains information about nonexistent ebuilds, causing Portage to refuse it.

**Comment by invakid404** [comment]
I regenerated the manifest and opened a pull request, check it out.

**Comment by Pross** [comment]
> I regenerated the manifest and opened a pull request, check it out.

Thx for that, i committed b4 i saw the pr :)
