### ISSUE TITLE
Bad digest for ck-sources

### ISSUE THREAD

**Issue by mothringer** [Pross/pross-overlay#3]
The digest for ck-sources needs to be regenerated, emerge is giving me the below error.

!!! Digest verification failed:
!!! /var/lib/layman/pross/sys-kernel/ck-sources/files/0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch
!!! Reason: Filesize does not match recorded size
!!! Got: 3786
!!! Expected: 4671

**Comment by Pross** [comment]
damn, try now?

**Comment by mothringer** [comment]
Appears to be fixed now.
