### ISSUE TITLE
gnome3.eclass could not be found by inherit

### ISSUE THREAD

**Issue by kartebi** [Pross/pross-overlay#6]
Calculating dependencies / * ERROR: x11-libs/gtk+-3.24.23-r1::pross failed (depend phase):
 *   gnome3.eclass could not be found by inherit()
 * 
 * Call stack:
 *                ebuild.sh, line 609:  Called source '/var/lib/layman/pross/x11-libs/gtk+/gtk+-3.24.23-r1.ebuild'
 - *   gtk+-3.24.23-r1.ebuild, line   7:  Called inherit 'flag-o-matic' 'gnome3' 'virtualx'
 *                ebuild.sh, line 290:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/gtk+-3.24.23-r1::pross'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/gtk+-3.24.23-r1::pross'`.
 * Working directory: '/usr/lib/python3.8/site-packages'
 * S: '/var/tmp/portage/x11-libs/gtk+-3.24.23-r1/work/gtk+-3.24.23'
 / * ERROR: x11-libs/gtk+-2.24.32-r2::pross failed (depend phase):
 *   gnome3.eclass could not be found by inherit()
 * 
 * Call stack:
 *                ebuild.sh, line 609:  Called source '/var/lib/layman/pross/x11-libs/gtk+/gtk+-2.24.32-r2.ebuild'
 *   gtk+-2.24.32-r2.ebuild, line   5:  Called inherit 'autotools' 'flag-o-matic' 'gnome3' 'readme.gentoo-r1' 'virtualx'
 *                ebuild.sh, line 290:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/gtk+-2.24.32-r2::pross'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/gtk+-2.24.32-r2::pross'`.
 * Working directory: '/usr/lib/python3.8/site-packages'
 * S: '/var/tmp/portage/x11-libs/gtk+-2.24.32-r2/work/gtk+-2.24.32'
... done!

**Comment by Pross** [comment]
Gentoo or Funtoo?

**Comment by kartebi** [comment]
gentoo

**Comment by Pross** [comment]
Ok, I added the eclasses, not sure if it'll work on Gentoo, might, might not.

**Comment by kartebi** [comment]
The eclass error is gone but there comes a new one
I'm on ~amd64 gentoo

Calculating dependencies | * ERROR: x11-libs/gtk+-3.24.23-r1::pross failed (depend phase):
 *   ltprune: banned in EAPI=7; use 'find' instead
 * 
 * Call stack:
 *                ebuild.sh, line 609:  Called source '/var/lib/layman/pross/x11-libs/gtk+/gtk+-3.24.23-r1.ebuild'
 *   gtk+-3.24.23-r1.ebuild, line   7:  Called inherit 'flag-o-matic' 'gnome3' 'virtualx'
 *                ebuild.sh, line 314:  Called __qa_source '/var/lib/layman/pross/eclass/gnome3.eclass'
 *                ebuild.sh, line 112:  Called source '/var/lib/layman/pross/eclass/gnome3.eclass'
 *            gnome3.eclass, line  20:  Called inherit 'eutils' 'libtool' 'gnome.org' 'gnome3-utils' 'xdg' 'ltprune'
 - *                ebuild.sh, line 314:  Called __qa_source '/var/db/repos/gentoo/eclass/ltprune.eclass'
 *                ebuild.sh, line 112:  Called source '/var/db/repos/gentoo/eclass/ltprune.eclass'
 *           ltprune.eclass, line  24:  Called die
 * The specific snippet of code:
 *              die "${ECLASS}: banned in EAPI=${EAPI}; use 'find' instead";;
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/gtk+-3.24.23-r1::pross'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/gtk+-3.24.23-r1::pross'`.
 * Working directory: '/usr/lib/python3.8/site-packages'
 * S: '/var/tmp/portage/x11-libs/gtk+-3.24.23-r1/work/gtk+-3.24.23'
 |

!!! Problem resolving dependencies for gtk+-2.24.32-r2.ebuild
... done!

!!! All ebuilds that could satisfy ">=x11-libs/pango-1.44.7[introspection?]" have been masked.
!!! One of the following masked packages is required to complete your request:
- x11-libs/pango-1.44.7::gentoo (masked by: package.mask)
/var/db/repos/gentoo/profiles/package.mask:
# Mart Raudsepp <leio@gentoo.org> (2020-02-03)
# Needs news item, known breakages that need to be handled first, bug 698922


(dependency required by "x11-libs/gtk+-2.24.32-r2::pross" [ebuild])
(dependency required by "gtk+-2.24.32-r2.ebuild" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

**Comment by Pross** [comment]
Looks like it isnt going to work on Gentoo then.

You could just add the patch I added to your user patches folder in /etc/portage/patches ?

**Comment by kartebi** [comment]
Ok, i'm a complete noob going about that
(btw ck-sources and bashtop work fine)
Tried to follow the instructions here https://wiki.gentoo.org/wiki//etc/portage/patches

**1. Tried gtk2 with the gtk2 patches in gtk+/files
run "ebuild gtk+-2.24.32-r2.ebuild clean prepare"**

* Running elibtoolize in: gtk+-2.24.32/
*   Applying portage/1.2.0 patch ...
*   Applying sed/1.5.6 patch ...
*   Applying as-needed/2.4.3 patch ...
* Applying gtk+-2.24.24-out-of-source.patch ...
patching file gtk/aliasfilescheck.sh
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- saving rejects to file gtk/aliasfilescheck.sh.rej                                                                                                                                                                                            [ !! ]
 * ERROR: x11-libs/gtk+-2.24.32-r2::pross failed (prepare phase):
 *   patch -p1  failed with /etc/portage/patches/x11-libs/gtk+-2.24.32-r2/gtk+-2.24.24-out-of-source.patch

**2. Tried gtk2 with the patches in gtk+/files/patches/
run "ebuild gtk+-2.24.32-r2.ebuild clean prepare"**

* Running elibtoolize in: gtk+-2.24.32/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.4.3 patch ...
 * Applying 0001-configure-Move-all-includes-to-the-first-argument-of.patch ...
patching file configure.ac
Hunk #1 FAILED at 715.
Hunk #2 FAILED at 726.
2 out of 2 hunks FAILED -- saving rejects to file configure.ac.rej                                                                                                                                                                                                     [ !! ]
 * ERROR: x11-libs/gtk+-2.24.32-r2::pross failed (prepare phase):
 *   patch -p1  failed with /etc/portage/patches/x11-libs/gtk+-2.24.32-r2/0001-configure-Move-all-includes-to-the-first-argument-of.patch

**3. Tried gtk3 with the gtk3 patches in gtk+/files and tried with the gtk+/files/patches/
run "ebuild gtk+-3.24.23-r1.ebuild clean prepare"
got the same "ltprune: banned in EAPI=7; use 'find' instead" error in my previous msg**

**Comment by Pross** [comment]
Yea, it isnt going to work with this rebuild on gentoo.

So what you need to do is mask this version for this repo. The copy the patch in the files folder here... all it does is add the thumbnails to the filepicker btw, nothing more.

Copy that patch to your patches folder for gtk+ so that when you install your normal gentoo version it uses my patch when it emerges

**Comment by kartebi** [comment]
Ok thanks, so the issue is closed ?
first time in github :)
who is closing this? me or you?

**Comment by Pross** [comment]
I can :)
